### ISSUE TITLE
VScode says that couple of scripts doesn't exist.

### ISSUE THREAD

**Issue by whatadayhuh** [sunderee/Mappy2#3]
> _Target of URI doesn't exist: 'response.model.freeze.dart'.
> Try creating the file referenced by the URI, or Try using a URI for a file that does exist._

> Target of URI doesn't exist: 'response.modelg.dart'.
> Try creating the file referenced by the URI, or Try using a URI for a file that does exist.

also

> The method '_$ResponseModelFromJson' isn't defined for the type 'ResponseModel'.
> Try correcting the name to the name of an existing method, or defining a method named '_$ResponseModelFromJson'.

> The method '_$FeatureModelFromJson' isn't defined for the type 'FeatureModel'.
> Try correcting the name to the name of an existing method, or defining a method named '_$FeatureModelFromJson'.

**Comment by sunderee** [comment]
Did you run the code generation task?

**Comment by whatadayhuh** [comment]
> Did you run the code generation task?

Yep

**Comment by sunderee** [comment]
Interesting... Are you getting any errors during the code generation task?

**Comment by whatadayhuh** [comment]
> Interesting... Are you getting any errors during the code generation task?

All good now. I fixed that. Thanks for the quick response.

**Comment by sunderee** [comment]
@whatadayhuh can you maybe share what had to happen for you to fix the error? Because on a bit unrelated note, I'm having problems with `build_runner` not building things completely in a professional project unrelated to this one.

**Comment by whatadayhuh** [comment]
> @whatadayhuh can you maybe share what had to happen for you to fix the error? Because on a bit unrelated note, I'm having problems with `build_runner` not building things completely in a professional project unrelated to this one.

Well the issue was because I accidentally renamed the model scripts and therefore they were not built correctly.
I was building this scripts over and over again til I noticed that I renamed those scripts :) 
After I fixed it, everything worked correctly.

**Comment by sunderee** [comment]
Okay that makes sense why it'd fail. Thank you for sharing, guess I will have to open an issue with `build_runner` haha

Anyways, have a good one :)
